name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Get latest Zig
      run: sudo snap install zig --classic --edge

    - name: Check out code 
      uses: actions/checkout@v1
      
    - name: PWD
      run: pwd && ls -lah
      
    - name: Run tests
      run: sudo zig test src/heyredis.zig
